// Copyright (c) Murat Khamatyanov. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#nullable disable

namespace WebDebug.Migrations;

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDebug.Data;

/// <summary>
/// EF Core model snapshot for <see cref="AppDbContext"/>.
/// This file is generated by EF Core migrations and represents the current database model.
/// </summary>
[DbContext(typeof(AppDbContext))]
public partial class AppDbContextModelSnapshot : ModelSnapshot
{
    /// <summary>
    /// Builds the EF Core model metadata used by migrations.
    /// </summary>
    /// <param name="modelBuilder">Model builder used to configure entity mappings.</param>
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

        modelBuilder.Entity("MyNUnitWeb.Domain.TestCaseResult", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("TEXT");

            b.Property<double>("DurationMs")
                .HasColumnType("REAL");

            b.Property<string>("FullName")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("Message")
                .HasColumnType("TEXT");

            b.Property<Guid>("RunId")
                .HasColumnType("TEXT");

            b.Property<string>("Status")
                .IsRequired()
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("RunId");

            b.ToTable("TestCaseResults");
        });

        modelBuilder.Entity("MyNUnitWeb.Domain.TestRun", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("TEXT");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("TEXT");

            b.Property<int>("Failed")
                .HasColumnType("INTEGER");

            b.Property<int>("Passed")
                .HasColumnType("INTEGER");

            b.Property<int>("Skipped")
                .HasColumnType("INTEGER");

            b.Property<int>("Total")
                .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.ToTable("TestRuns");
        });

        modelBuilder.Entity("MyNUnitWeb.Domain.TestCaseResult", b =>
        {
            b.HasOne("MyNUnitWeb.Domain.TestRun", null)
                .WithMany("Results")
                .HasForeignKey("RunId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("MyNUnitWeb.Domain.TestRun", b =>
        {
            b.Navigation("Results");
        });
#pragma warning restore 612, 618
    }
}